"""сhange max len raw_text in news_items

Revision ID: 1baefdc792b6
Revises: a2abc7090d7c
Create Date: 2026-02-13 13:22:33.176202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1baefdc792b6'
down_revision: Union[str, Sequence[str], None] = 'a2abc7090d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_items', 'raw_text',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=4100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_items', 'raw_text',
               existing_type=sa.String(length=4100),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###
