"""add user_post table

Revision ID: 81c8619c0113
Revises: d33dfaff3e42
Create Date: 2026-02-10 13:05:17.192820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c8619c0113'
down_revision: Union[str, Sequence[str], None] = 'd33dfaff3e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PUBLISHED', 'FAILED', name='userspoststatus', native_enum=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_post')
    # ### end Alembic commands ###
