"""change enam in news_items

Revision ID: b24442669792
Revises: f224092fe164
Create Date: 2026-02-27 11:04:44.173741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24442669792'
down_revision: Union[str, Sequence[str], None] = 'f224092fe164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_items', 'status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('NEW', 'SIMHASH_DEDUPLICATED', 'VECTOR_DEDUPLICATED', 'PROCESSED', 'FAILED', name='newsitemstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_items', 'status',
               existing_type=sa.Enum('NEW', 'SIMHASH_DEDUPLICATED', 'VECTOR_DEDUPLICATED', 'PROCESSED', 'FAILED', name='newsitemstatus', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
