"""add last_login in admins

Revision ID: d7b8e3b4e3fc
Revises: c6e3b2d09f4b
Create Date: 2026-02-17 15:40:02.034368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b8e3b4e3fc'
down_revision: Union[str, Sequence[str], None] = 'c6e3b2d09f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'last_login')
    # ### end Alembic commands ###
